### PR TITLE
Size settings for non-svg images and inclusion of xml+svg in Settings

### PR DESCRIPTION
**Pull request by xenatisch**
- Rectified the error causing image size alteration for non-svg images being ignored. 
- Additionally, broke down pieces of code into task-specific functions inline with functional/OOP programming best practices, but also to make them easier to read and debug. 
- `image/xml+svg` is now included in the default settings. 
- Also tested on Python 3.6 - works perfectly fine. 

_Reminder_: This would require a minor version change + pipy update as the error I found was preventing the application from performing one of the preceding features.

### CODE REVIEW

**Comment by adi-** [comment]
Have you tried the v1.7 version? v1.7 already supports uploading SVGs.

**Comment by xenatisch** [comment]
Yeah. I wrote it myself! :D 
There is a minor bug that I fixed in this one, and added it to the default settings.

**Comment by adi-** [comment]
Omg! Ok, so please update it to v.1.7.1 because some additional fixes were already added.

**Comment by xenatisch** [comment]
Sure. I'll close this and rebase my version, then do another pull request.

**Comment by adi-** [comment]
Great and thanx!

Btw, I like your coding style a lot. Would you like to be added to this project? It needs documenting and tests to be added.

**Comment by xenatisch** [comment]
After 15+ years of coding, I've come to appreciate best practices, and tend to stick to them as much as practically possible. 

Sure... why not. I'd love to help.

**Comment by adi-** [comment]
Invitation sent.

**Comment by xenatisch** [comment]
And gratefully accepted. Thanks :)

**Pull request closed without merging**
