### PR TITLE
Fix #50 -- Native template-based widget rendering.

### LINKED ISSUE #50: Compatibility with Django 1.11
Django 1.11 provides template-based widget rendering.

That's good news, because django-markdownx no longer needs to roll its own, but also bad news, because the current implementation breaks.

I made a quick implementation that appears to work on Django 1.11b1 with the following changes.

1. Create a `widget2.html` template next to `widget.html` with the following content:

```html
<div class="markdownx">
    {% include 'django/forms/widgets/textarea.html' %}
    <div class="markdownx-preview"></div>
</div>
```

2. Replace the implementation of `MarkdownxWidget` with:

```python
class MarkdownxWidget(forms.Textarea):
    template_name = 'markdownx/widget2.html'

    def get_context(self, name, value, attrs=None):
        if attrs is None:
            attrs = {}

        if 'class' in attrs:
            attrs['class'] += ' markdownx-editor'
        else:
            attrs.update({'class': 'markdownx-editor'})

        attrs['data-markdownx-editor-resizable'] = MARKDOWNX_EDITOR_RESIZABLE
        attrs['data-markdownx-urls-path'] = MARKDOWNX_URLS_PATH
        attrs['data-markdownx-upload-urls-path'] = MARKDOWNX_UPLOAD_URLS_PATH

        return super(MarkdownxWidget, self).get_context(name, value, attrs)

    class Media:
        js = (
            'markdownx/js/markdownx.js',
        )
```

In order to keep compatibility with earlier version of django, you'll probably want to do something like:

```python
class MarkdownxWidget(forms.Textarea):
    if django.VERSION[:2] >= (1, 11):
        """new implementation goes here"""
    else:
        """current implementation stays here"""
```

It's a bit too late here to turn this suggestion into a proper pull request, but I hope this helps anyway!

### PR DESCRIPTION
**Pull request by aaugustin**
Same PR, but against the correct branch.

### CODE REVIEW

**Comment by xenatisch** [comment]
Once again, thanks. 

I know the travis tests pass, but I take it you have also tested this in practice for both Django ±1.11 too, right? 

Our tests are not yet as comprehensive as we'd like them to be (working on that too).

**Comment by aaugustin** [comment]
Yes, I did a smoke test on Django 1.10 and 1.11.

In both cases, the widget displays as expected and the live preview works.

**Comment by aaugustin** [comment]
We have an implementation for Django >= 1.11 and a totally different implementation for Django < 1.11. This is less visible after 9d60c5604547b138a7439d354f7e71fd641cabf6. But whatever works for you :-)

**Comment by xenatisch** [comment]
I agree that it might be less visible (I'll point it out in the docs). However, I am fundamentally against using logics in the main body of a class unless it is absolutely necessary. It also increases indentation levels unnecessarily, and makes `help()` functions / generated docs look really weird. 

This is one of the instances that one has to choose between best practice, functionality, and readability.

**Comment by xenatisch** [comment]
Right... I'm sick of working on GitHub. I'm gonna merge this and do anything I need locally. I think we can merge them all in one function to address your point in terms of readability. 

Once again, thanks for this. Great help.

**Pull request merged**
