### PR TITLE
Added three more triggers into the JS

### PR DESCRIPTION
**Pull request by ribalba**
I added three more triggers that are triggered on file upload, on success and on failure. So it is possible t change the interface to reflect file uploading in progress.

### CODE REVIEW

**Comment by xenatisch** [comment]
I'm working on pure JavaScript instead of JQuery; or rather, I was. If I ever get it done, I shall have to do this too. Although we might need to stick to Ajax as the XMLRequest can get very tedious very quickly. 

Anyhow, the code looks fine. Is it tested? Everything works as it should? 

Also, care to write a few lines of guidance for the `README.md` file? We're working on the docs, but in the meantime, it's good to have a reference to every useful feature over there.

**Comment by ribalba** [comment]
Yes, I tested it locally. I added it to the Readme?

**Comment by xenatisch** [comment]
Oh yes, you did. Sorry, I only looked at the changes, and they were JS codes. Didn't look at the filename. 

Thanks :)

**Comment by adi-** [comment]
Xenatish, since github is so dumb, abd don't allow to send direct messages, please send me your contact info to aaadeji at gmail dot com

**Comment by xenatisch** [comment]
@adi-  done

**Pull request merged**
